### ISSUE TITLE
Error: Cannot find module '@babel/types'

### ISSUE THREAD

**Issue by bosu1787** [mwraith/homebridge-somfi-blinds#2]
hello the plugin gives me an error 

====================
[20.01.2022, 20:50:02] ERROR LOADING PLUGIN homebridge-somfi-blinds:
[20.01.2022, 20:50:02] Error: Cannot find module '@babel/types'
Require stack:
- /usr/lib/node_modules/homebridge-somfi-blinds/lib/SomfyRtsRemoteAccessory.js
- /usr/lib/node_modules/homebridge-somfi-blinds/lib/index.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-somfi-blinds/lib/SomfyRtsRemoteAccessory.js:24:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
[20.01.2022, 20:50:02] ====================

**Comment by mwraith** [comment]
Hi @bosu1787

I pushed v0.2 with a fix to the dependencies. Can you please try and let me know?

**Comment by bosu1787** [comment]
still got this error

[21.01.2022, 08:23:07] No plugin was found for the accessory "Somfy Blinds Remote" in your config.json. Please make sure the corresponding plugin is installed correctly.
[21.01.2022, 08:23:07] No plugin was found for the accessory "Somfy Blinds Remote" in your config.json. Please make sure the corresponding plugin is installed correctly.

**Comment by bosu1787** [comment]
changing in config.json from "accessory": "Somfy Blinds Remote"     to "accessory": "Somfy Blinds"   works. do you know if we can change the icon type from switch to blinds or curtains? that will be nice :) like native.

**Comment by bosu1787** [comment]
@mwraith update 0.2.1 didnt fix the accessory name. still got this error:

21.01.2022, 13:53:48] No plugin was found for the accessory "Somfy Blinds Remote" in your config.json. Please make sure the corresponding plugin is installed correctly.
[21.01.2022, 13:53:48] No plugin was found for the accessory "Somfy Blinds Remote" in your config.json. Please make sure the corresponding plugin is installed correctly.
[21.01.2022, 13:53:48] No plugin was found for the accessory "Somfy Blinds Remote" in your config.json. Please make sure the corresponding plugin is installed correctly.
[21.01.2022, 13:53:48] No plugin was found for the accessory "Somfy Blinds Remote" in your config.json. Please make sure the corresponding plugin is installed correctly.

**Comment by mwraith** [comment]
I left the accessory name as "Somfy Blinds" but just changed the default config so that the next user setting up from scratch should get the right value without having to modify the config manually.

I took a quick look at the icon type. There's no way to override it. I suspect in HomeBridge the [Window Covering](https://developers.homebridge.io/#/service/WindowCovering) service type would show a better icon, but the problem is it then doesn't work as an on/off switch but rather a % open. Given there is no way to properly control % opening as the device doesn't report a state and using timing would be super flakey, I think I'd rather leave it as a switch and accept the icon. Open to other views though.

**Comment by bosu1787** [comment]
from what i know from mqtt i think is an option you can enable with % or only close and open. same as for the fan. for exemple for fan you have an option with% or only on&off

**Comment by bosu1787** [comment]
yep i checked apple homekit have window covering only with % mabe in the future we will able to change icon directly from home app. :)

**Comment by mwraith** [comment]
@bosu1787 The window covering icon feature is now available. I realised that although you have to set a %, you can set a step-size that forces it to be fully open or fully closed.

**Comment by bosu1787** [comment]
@mwraith wow nice :D best plugin ever. thank you.
